<div style="clear:both"></div>
<div class="product_editor_note">
    <div class="product_links">
        <ul>
            <li>Jonathan Simkhai</li>
            <li>Blazers</li>
            <li>Viscose</li>
        </ul>
    </div>
    <div class="title">
        <p>a note from the editor</p>
    </div>
    <div class="message_container">
        <p class="message">
            The Forte Lurex Linen Viscose Jacket in Mother of Pearl features lunar lavishness by night and by day: a blazer in a linen blend shot with lurex for a shimmering surface that shines like a star in the sky. 
        </p>
    </div>        
    <div class="author">
        <p>
            <span>&#9135&#9135</span> By <span class="name">MINNA SHIM,</span> Fashion Editor
        </p>
    </div>
</div>

